import React from 'react';
import { useEffect } from 'react';

const staff =[
    {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Simphile Mkhize",
        "Email": "2544782@students.wits.ac.za",
        "Phone": "+27739122901",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": "B21",
        "onPremises": true,
        "HashedPassword": "36dTotv8UV",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Lusanda Shongwe",
        "Email": "2544636@students.wits.ac.za",
        "Phone": "+27706238208",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": null,
        "onPremises": true,
        "HashedPassword": "tPqXEwmhlL",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Nkosinathi Phiri",
        "Email": "2627971@students.wits.ac.za",
        "Phone": "+27902739731",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": "D34",
        "onPremises": true,
        "HashedPassword": "yUPdDozh4w",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Katleho Myeza",
        "Email": "2582393@students.wits.ac.za",
        "Phone": "+27756326299",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": null,
        "onPremises": true,
        "HashedPassword": "lLTKL07KZ1",
        "Permissions ": "[list of permissions]"
      },
      {
          "PersonID": "generated by mongo",
          "Role": "Admin",
          "Name": "Mbuyu Kasongo",
          "Email": "2499924@students.wits.ac.za",
          "Phone": "+27986882339",
          "BiometricData": "...",
          "PropertyName": "Windsor Heights",
          "UnitID": null,
          "onPremises": true,
          "HashedPassword": "T8WpUl1kTv",
          "Permissions ": "[list of permissions]"
      }
  ];

function Staff() {
    
 

    return (
        <>
            {staff.map((person, index) => (
                <div key={index} className="comp">
                    <article className="insComp">
                        <section className="profile">
                            <img src="pp.png" alt="" />
                            <p className="name">
                                {person.Name}
                            </p>
                        </section>
                        <ul className="vC">
                            <li className="variables">{person.Email}</li>
                            <li className="variables">{person.Role}</li>
                            <li className="variables">{person.UnitID}</li>
                        </ul>
                    </article>
                </div>
            ))}
        </>
    );
}

function StaffValue() {
    return (
        <p id="Num_stuff">{staff.length}</p>
    );
}

export { StaffValue }; // Export Value as a named export
export default Staff; // Export Residents as the default export
