import React from "react";
const staff =[
    {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Simphile Mkhize",
        "Email": "2544782@students.wits.ac.za",
        "Phone": "+27739122901",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": "B21",
        "onPremises": true,
        "Access":"Denied",
        "HashedPassword": "36dTotv8UV",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Lusanda Shongwe",
        "Email": "2544636@students.wits.ac.za",
        "Phone": "+27706238208",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID":"4",
        "Access":"Granted",
        "onPremises": true,
        "HashedPassword": "tPqXEwmhlL",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Nkosinathi Phiri",
        "Email": "2627971@students.wits.ac.za",
        "Phone": "+27902739731",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": "D34",
        "Access":"Denied",
        "onPremises": true,
        "HashedPassword": "yUPdDozh4w",
        "Permissions ": "[list of permissions]"
      },
      {
        "PersonID": "generated by mongo",
        "Role": "Admin",
        "Name": "Katleho Myeza",
        "Email": "2582393@students.wits.ac.za",
        "Phone": "+27756326299",
        "BiometricData": "...",
        "PropertyName": "Windsor Heights",
        "UnitID": "8",
        "onPremises": true,
        "Access":"Granted",
        "HashedPassword": "lLTKL07KZ1",
        "Permissions ": "[list of permissions]"
      },
      {
          "PersonID": "generated by mongo",
          "Role": "Admin",
          "Name": "Mbuyu Kasongo",
          "Email": "2499924@students.wits.ac.za",
          "Phone": "+27986882339",
          "BiometricData": "...",
          "PropertyName": "Windsor Heights",
          "UnitID": "9",
          "onPremises": true,
          "HashedPassword": "T8WpUl1kTv",
          "Permissions ": "[list of permissions]",
          "Access":"Granted"
      }
  ];


function workInforStuff ({personName}) {
            const person = staff.find(person => person.UnitID == personName);
            if (!person) {
                return <p>No resident found with that name.</p>;
            }
            return(
                    <ul>
                        <li><p>Role:</p> <h6>{person.Role}</h6></li>
                        <li><p>UnitID:</p> <h6>{person.UnitID}</h6></li>
                        <li><p>onPremises:</p> <h6>{person.onPremises}</h6></li>
                        <li><p>onPremises:</p> <h6>{person.onPremises}</h6></li>
                        <li><p>Access:</p> <h6>{person.Access}</h6></li>
                    </ul>
                )
            };       

export default workInforStuff;